(function($) {
    $(document).ready(function() {
	
	$('#Sinewave').scianimator({
	    'images': ['images/Sinewave1.png', 'images/Sinewave2.png', 'images/Sinewave3.png', 'images/Sinewave4.png', 'images/Sinewave5.png', 'images/Sinewave6.png', 'images/Sinewave7.png', 'images/Sinewave8.png', 'images/Sinewave9.png', 'images/Sinewave10.png', 'images/Sinewave11.png', 'images/Sinewave12.png', 'images/Sinewave13.png', 'images/Sinewave14.png', 'images/Sinewave15.png', 'images/Sinewave16.png', 'images/Sinewave17.png', 'images/Sinewave18.png', 'images/Sinewave19.png', 'images/Sinewave20.png', 'images/Sinewave21.png', 'images/Sinewave22.png', 'images/Sinewave23.png', 'images/Sinewave24.png', 'images/Sinewave25.png', 'images/Sinewave26.png', 'images/Sinewave27.png', 'images/Sinewave28.png', 'images/Sinewave29.png', 'images/Sinewave30.png', 'images/Sinewave31.png', 'images/Sinewave32.png', 'images/Sinewave33.png', 'images/Sinewave34.png', 'images/Sinewave35.png', 'images/Sinewave36.png', 'images/Sinewave37.png', 'images/Sinewave38.png', 'images/Sinewave39.png', 'images/Sinewave40.png', 'images/Sinewave41.png', 'images/Sinewave42.png', 'images/Sinewave43.png', 'images/Sinewave44.png', 'images/Sinewave45.png', 'images/Sinewave46.png', 'images/Sinewave47.png', 'images/Sinewave48.png', 'images/Sinewave49.png', 'images/Sinewave50.png', 'images/Sinewave51.png', 'images/Sinewave52.png', 'images/Sinewave53.png', 'images/Sinewave54.png', 'images/Sinewave55.png', 'images/Sinewave56.png', 'images/Sinewave57.png', 'images/Sinewave58.png', 'images/Sinewave59.png', 'images/Sinewave60.png', 'images/Sinewave61.png', 'images/Sinewave62.png', 'images/Sinewave63.png', 'images/Sinewave64.png', 'images/Sinewave65.png', 'images/Sinewave66.png', 'images/Sinewave67.png', 'images/Sinewave68.png', 'images/Sinewave69.png', 'images/Sinewave70.png', 'images/Sinewave71.png', 'images/Sinewave72.png', 'images/Sinewave73.png', 'images/Sinewave74.png', 'images/Sinewave75.png', 'images/Sinewave76.png', 'images/Sinewave77.png', 'images/Sinewave78.png', 'images/Sinewave79.png', 'images/Sinewave80.png', 'images/Sinewave81.png', 'images/Sinewave82.png', 'images/Sinewave83.png', 'images/Sinewave84.png', 'images/Sinewave85.png', 'images/Sinewave86.png', 'images/Sinewave87.png', 'images/Sinewave88.png', 'images/Sinewave89.png', 'images/Sinewave90.png', 'images/Sinewave91.png', 'images/Sinewave92.png', 'images/Sinewave93.png', 'images/Sinewave94.png', 'images/Sinewave95.png', 'images/Sinewave96.png', 'images/Sinewave97.png', 'images/Sinewave98.png', 'images/Sinewave99.png', 'images/Sinewave100.png'],
	    'width': 480,
	    'delay': 20,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
	$('#Sinewave').scianimator('play');
    });
})(jQuery);
