---
title: "Graphics"
author: "Elara"
date: "2016年6月3日"
output: html_document
---

# Other graphs          
## Stem and Leaf Plots茎叶图            
```{r}
x<-c(25, 45, 50, 54, 55, 61, 64, 68, 72, 75, 75,
78, 79, 81, 83, 84, 84, 84, 85, 86, 86, 86,
87, 89, 89, 89, 90, 91, 91, 92, 100)
stem(x)
stem(x,scale=2)#10分成scale=2部分，0-4和5-9（前一个再细分）
stem(x,scale=.5)#10分成0.5部分，相当于10作为半组，相当于20为一组
```

## Bar plots 柱状图  
barplot(height)         
```{r}
library(vcd)
counts <- table(Arthritis$Improved)
counts
opar<-par(no.readonly = TRUE)
par(mfrow = c(1, 2))
barplot(counts, main = "Simple Bar Plot", xlab = "Improvement", ylab = "Frequency")
barplot(counts, main = "Horizontal Bar Plot", xlab = "Frequency",
ylab = "Improvement", horiz = TRUE,
names.arg=c("A","B","C"))#horiz转置
par(opar)
```

### Stacked and grouped bar plots               
```{r}
library(vcd)
counts <- table(Arthritis$Improved, Arthritis$Treatment)
counts
opar<-par(no.readonly = TRUE)
par(mfrow = c(1, 2))
barplot(counts, main="Stacked Bar Plot", xlab="Treatment",
ylab="Frequency", col=c("red", "yellow","green"), legend=rownames(counts))#legend加图例，改色
barplot(counts, main="Grouped Bar Plot", xlab="Treatment",
ylab="Frequency", col=c("red", "yellow", "green"),
legend=rownames(counts), beside=TRUE)#beside分离,分组分颜色累积柱状图
par(opar)
```

#Mean bar plots         
```{r}
states <- data.frame(state.region, state.x77)
means <- aggregate(states$Illiteracy, by = list(state.region),
FUN = mean)
means
means <- means[order(means$x), ]
means
barplot(means$x, names.arg = means$Group.1)
title("Mean Illiteracy Rate")
```

## Pie charts           
```{r}
par(mfrow = c(2, 2))
#1平面饼图
slices <- c(10, 12, 4, 16, 8)
lbls <- c("US", "UK", "Australia", "Germany", "France")
pie(slices, labels = lbls, main = "Simple Pie Chart")
#2平面饼图带百分比
pct <- round(slices/sum(slices) * 100)
lbls2 <- paste(lbls, " ", pct, "%", sep = "")
pie(slices, labels = lbls2, col = rainbow(length(lbls)),
main = "Pie Chart with Percentages")
#3 3d饼图
library(plotrix)
pie3D(slices, labels = lbls, explode = 0.1, main = "3D Pie Chart ")
#4 饼图带频数
mytable <- table(state.region)
lbls <- paste(names(mytable), "\n", mytable, sep = "")
pie(mytable, labels = lbls, main = "Pie Chart from a Table\n (with sample sizes)")
```

## Kernel density plots密度图         
```{r}
par(mfrow = c(2, 1))
d <- density(mtcars$mpg)
plot(d)
d <- density(mtcars$mpg)
plot(d, main = "Kernel Density of Miles Per Gallon")
polygon(d, col = "red", border = "blue")#在上一张图中填充红色，轮廓蓝色
rug(mtcars$mpg, col = "brown")#在上一张图中加须
```

```{r}
#par(lwd = 2)
#library(sm)
#attach(mtcars)
#cyl.f <- factor(cyl, levels = c(4, 6, 8), labels = c("4 cylinder", "6 cylinder", "8 cylinder"))
#sm.density.compare(mpg, cyl, xlab = "Miles Per Gallon")
#title(main = "MPG Distribution by Car Cylinders")
#colfill <- c(2:(1 + length(levels(cyl.f))))
#cat("Use mouse to place legend...", "\n\n")#打印文字
#legend(locator(1), levels(cyl.f), fill = colfill)#鼠标指定放图例
#detach(mtcars)
#par(lwd = 1)
```

## Histograms直方图           
```{r}
par(mfrow = c(1, 2))
hist(mtcars$mpg, breaks = 7, col = "yellow", xlab = "Miles Per Gallon",
main = "Colored histogram with 12 bins")
hist(mtcars$mpg, freq = FALSE, breaks = 12, col = "red",#分12次柱子
     xlab = "Miles Per Gallon",
main = "Histogram, rug plot, density curve")
rug(mtcars$mpg)#加须
lines(density(mtcars$mpg), col = "blue", lwd = 2)
box()#把图围起来
```

## box plots 箱线图   
```{r}
boxplot(mtcars$mpg, main="Box plot", ylab="Miles per Gallon")
boxplot.stats(mtcars$mpg)#箱线图信息
par(mfrow = c(1, 2))
#按照cyl分类
boxplot(mpg ~ cyl, data = mtcars, main = "Car Milage Data",
xlab = "Number of Cylinders", ylab = "Miles Per Gallon")
mtcars$cyl.f <- factor(mtcars$cyl, levels = c(4, 6, 8),
labels = c("4", "6", "8"))
mtcars$am.f <- factor(mtcars$am, levels = c(0, 1),
labels = c("auto", "standard"))
#分类箱线图并上色
boxplot(mpg ~ am.f * cyl.f, data = mtcars, varwidth = TRUE, col = c("gold", "darkgreen"),
main = "MPG Distribution by Auto Type", xlab = "Auto Type")
```

## Dot plots            
```{r}
#windows(width = 7, height = 4)
par(mfrow = c(1, 2))
dotchart(mtcars$mpg, labels = row.names(mtcars), cex = 0.7,
main = "Gas Milage for Car Models", xlab = "Miles Per Gallon")
#加入color因子用于分类
x <- mtcars[order(mtcars$mpg),]
x$cyl <- factor(x$cyl)
x$color[x$cyl == 4] <- "red"
x$color[x$cyl == 6] <- "blue"
x$color[x$cyl == 8] <- "darkgreen"
#groups分类数据，color分组颜色
dotchart(x$mpg, labels = row.names(x), cex = 0.7, pch = 19,
groups = x$cyl, gcolor = "black", color = x$color,
main = "Gas Milage for Car Models\ngrouped by cylinder",
xlab = "Miles Per Gallon")
```

# Bubble plots          
symbols()画形状

```{r}
attach(mtcars)
symbols(wt, mpg, circle=disp)#circle表示圈大小
r <- sqrt(disp/pi)#缩小大小变化
symbols(wt, mpg, circle=r, inches=0.30,
        #inches标准化大小，true以最大为1，0.3表示最大的限制0.3英寸
fg="white", bg="lightblue",
main="Bubble Plot with point size proportional to displacement",
ylab="Miles Per Gallon", xlab="Weight of Car (lbs/1000)")
text(wt, mpg, rownames(mtcars), cex=0.6)
detach(mtcars)
```















