---
title: "Chinese Yuan and Stock Market 6-7"
author: "Wang ZeXian"
date: "2016年5月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message=FALSE)
```

# Exchange Rate CNY/USD
State Space Time Series Models Using DLM package
# Using Quandl API to search and retrieve data series
```{r}
# install.packages("Quandl")
library(Quandl)
# Quandl.auth("4UqGASL7CigqHzpfdnNw")
# SP500<-Quandl(code="YAHOO/INDEX_GSPC",type="xts") 
# xts or zoo type should be used for daily high frequency data
# frequency conversion for xts type: apply.xxx
# xxx=yearly, quartertly, monthly, weekly
#CNY<-Quandl(code="BUNDESBANK/BBEX3_D_CNY_USD_CA_AC_000",type="xts") 
# daily price index: irregularly-spaced time series
# CNY<-subset(CNY,time(CNY)>c("2005-12-31"))
load("C:\\Users\\44180\\Documents\\R-in-SOE\\R\\big data\\case6\\CNY.RData")
summary(CNY)
plot(CNY)
```
# dummy variable for structural change(set a dummy variable)
```{r}
d2006<-xts(ifelse(time(CNY)>c("2005-12-31"),1,0),order.by=time(CNY))
```
# select variable for analysis
```{r}
Y<-CNY

ols3<-lm(Y~d2006)
summary(ols3)# it does has a structal change impact (shown in coefficient)
```
#DLM
```{r}
library(dlm)

# local level with intervention variable
ssm3<-function(params) {
  dlmModReg(d2006,dV=exp(params[1]),dW=exp(params[2:3]))
        #suppose only a structual change rather than slope(trend)
        #dv
        #dw:state equations,1 is the level 2 is the structual change(dummy)
}
# constant level: dW=0 restricted
ssm3a<-function(params) {
  dlmModReg(d2006,dV=exp(params[1]),dW=c(exp(params[2]),0))
        #dw[2]is 0,cause we suppose no structual change(dummy=0)
}

# ML Estimation 
ssm.fit<-dlmMLE(Y,c(1,1,1),ssm3)
ssm.fit
ssm.model<-ssm3(ssm.fit$par)
ssm.model#
ssm.model$V  # V(ssm1.model)
ssm.model$W  # W(ssm1.model)
ssm.filtered<-dlmFilter(Y,ssm.model)
ssm.smoothed<-dlmSmooth(ssm.filtered)
ssm.resid<-residuals(ssm.filtered)$res
ssm.sm<-dropFirst(ssm.smoothed$s)  # smoothed mu
summary(ssm.sm)
ts.plot(ssm.sm[,1])
ts.plot(ssm.sm[,2]) # parameter of d2006

acf(ssm.resid)
pacf(ssm.resid)
```